import dotenv from 'dotenv'
dotenv.config()

const MONGODB_URL = process.env.MONGODB_URL
const REDIS_URL = process.env.REDIS_URL
const EMAIL_SERVICE = process.env.EMAIL_SERVICE
const EMAIL_HOST = process.env.EMAIL_HOST
const EMAIL_USER = process.env.EMAIL_USER
const EMAIL_PASS = process.env.EMAIL_PASS
const BASE_URL = process.env.BASE_URL
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET
const GOOGLE_REDIRECT_URL = process.env.GOOGLE_REDIRECT_URL
const FRONTEND_BASE_URL = process.env.FRONTEND_BASE_URL
const FRONTEND_ERROR_URL = process.env.FRONTEND_ERROR_URL
const JWT_ACCESS_TOKEN_SECRET = process.env.JWT_ACCESS_TOKEN_SECRET
const JWT_REFRESH_TOKEN_SECRET = process.env.JWT_REFRESH_TOKEN_SECRET

export {
  MONGODB_URL, 
  REDIS_URL,
  EMAIL_SERVICE,
  EMAIL_HOST,
  EMAIL_USER,
  EMAIL_PASS,
  BASE_URL,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URL,
  FRONTEND_BASE_URL,
  FRONTEND_ERROR_URL,
  JWT_ACCESS_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_SECRET
}