import dotenv from 'dotenv'
dotenv.config()

const MONGODB_URL = process.env.MONGODB_URL
const REDIS_HOST = process.env.REDIS_HOST
const REDIS_USER = process.env.REDIS_USER
const REDIS_PASSWORD = process.env.REDIS_PASSWORD
const REDIS_PORT = process.env.REDIS_PORT
const EMAIL_SERVICE = process.env.EMAIL_SERVICE
const EMAIL_HOST = process.env.EMAIL_HOST
const EMAIL_USER = process.env.EMAIL_USER
const EMAIL_PASS = process.env.EMAIL_PASS
const BASE_URL = process.env.BASE_URL
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET
const GOOGLE_REDIRECT_URL = process.env.GOOGLE_REDIRECT_URL
const FRONTEND_BASE_URL = process.env.FRONTEND_BASE_URL
const FRONTEND_ERROR_URL = process.env.FRONTEND_ERROR_URL
const FRONTEND_RESET_PASSWORD_URL = process.env.FRONTEND_RESET_PASSWORD_URL
const JWT_ACCESS_TOKEN_SECRET = process.env.JWT_ACCESS_TOKEN_SECRET
const JWT_REFRESH_TOKEN_SECRET = process.env.JWT_REFRESH_TOKEN_SECRET
const MIDTRANS_SERVER_KEY = process.env.MIDTRANS_SERVER_KEY
const ACCESS_TOKEN_EXPIRE_MINUTE = process.env.ACCESS_TOKEN_EXPIRE_MINUTE
const REFRESH_TOKEN_EXPIRE_DAY = process.env.REFRESH_TOKEN_EXPIRE_DAY
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET

export {
  MONGODB_URL, 
  REDIS_HOST,
  REDIS_USER,
  REDIS_PASSWORD,
  REDIS_PORT,
  EMAIL_SERVICE,
  EMAIL_HOST,
  EMAIL_USER,
  EMAIL_PASS,
  BASE_URL,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URL,
  FRONTEND_BASE_URL,
  FRONTEND_ERROR_URL,
  JWT_ACCESS_TOKEN_SECRET,
  JWT_REFRESH_TOKEN_SECRET,
  MIDTRANS_SERVER_KEY,
  ACCESS_TOKEN_EXPIRE_MINUTE,
  REFRESH_TOKEN_EXPIRE_DAY,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  FRONTEND_RESET_PASSWORD_URL
}